### ISSUE TITLE
Is priviledge=true needed mandatory

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/home-assistant-raspberry-zwave#2]
When starting up the docker-container, we see 

```
hass    | hostname: the specified hostname is invalid
hass    | mount: permission denied
hass    | mount: permission denied
hass    | mount: permission denied
hass    | mount: permission denied
hass    | mount: mount point /tmp/console is not a directory
hass    | umount: /dev: must be superuser to unmount
hass    | mount: permission denied
```

when not using `privileged=true` in the docker-compose / container configuration. Eventhough we already forward the devices to let the container access the tty device of our z-wave controller.

When we use privileged mode, we see

```
hass    | hostname: the specified hostname is invalid
hass    | mount: special device /dev/console does not exist
```

**Comment by EugenMayer** [comment]
After installing z-way and pairing my fist device on the host ( not in the docker-container ) i finally do not have any z-wave errors in the log and it seems to work. So at least, privileged=true is not mandatory for this - might cause other issues though

**Comment by mehuman** [comment]
Here's documentation on privilege. If the devices are being defined in the docker-compose file then privilege=true is not needed. Can you link to where you are seeing privilege=true? I couldn't find it in a quick glance around.

https://docs.docker.com/engine/reference/run/#/runtime-privilege-and-linux-capabilities

**Comment by EugenMayer** [comment]
@mehuman i know the documentation, but it does not help here :)

the problem is the docker-image, it seems to try to bind arbitrary /dev devices, the console or something else. I am yet not sure it even works with just exposing the device. The person tried it i addition to me could get the controller recognized with devices, but he could not bind ay z-wave device. 

He yet had not time trying the privileged mode and i do yet not have an actor ( ordered one ) so i am still not sure how far we get with unprivileged.

**Comment by mehuman** [comment]
Hmm, Docker should directly pass through whatever device you define in the compose. Mine works fine with a passed through bluetooth device.

When you say arbitrary /dev devices do you mean it's not binding the devices you are defining? Have you tried binding z-wave devices on the host system without docker?

**Comment by EugenMayer** [comment]
No, that works, but look at this: 

```

hass    | hostname: the specified hostname is invalid
hass    | mount: permission denied
hass    | mount: permission denied
hass    | mount: permission denied
hass    | mount: permission denied
hass    | mount: mount point /tmp/console is not a directory
hass    | umount: /dev: must be superuser to unmount
hass    | mount: permission denied

```

That is, with configured device and meanst, something is still trying to mount / access / link into something else into /dev which is not available when privileged is not used. And its a pitty there is 0 documentation in HASS for that

**Comment by mehuman** [comment]
I see. You are using a zwave controller that works through the rpi pins and not usb. Can you take a look at this and see if any of that helps? To use privilege=false you will need to pass through the rpi pins device so HA can communicate with it. If it works I'm happy to help add the findings to the HA docs.
http://blog.hypriot.com/post/lets-get-physical/

**Comment by EugenMayer** [comment]
Already doing that https://github.com/EugenMayer/home-assistant-raspberry-zwave/blob/master/docker/docker-compose.yml#L16

Or did i get confused? this is exactly the tty device my GPIO uses, it also works when i use z-way on the host device and it is publicly confirmed

**Comment by mehuman** [comment]
No you should be right. I unfortunately don't have the hardware you are using so I can't help test. I'll try digging around to see if I can find something though.

**Comment by EugenMayer** [comment]
It is not mandatory, i could get hass work without it, controlling a Fibaro Shutter without issues
