### ISSUE TITLE
Do we really need network_mode: "host" for the container?

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/home-assistant-raspberry-zwave#4]
I am not sure why this is needed, probably its about multi-cast / broadcast?
As an alternative we could expose the ports in question to the host : 
 - 8123
 - ?

Are there any reasons for the network to be bound on the host container as a whole?

**Comment by mehuman** [comment]
There is no real reason for network to be bound to host other than there are a bunch of ports that are needed for the auto discovery. It's recommended to be configured that way to make it easier than defining all the ports needed. I'd love to be able to get a full list of all the ports used and be able to define them when creating my container though. Also according to the Docker docs host networking is faster than other types, not that HA is a high IO application.

https://docs.docker.com/engine/reference/run/#/network-settings

**Comment by EugenMayer** [comment]
Yes host mode is faster, but only in specific condition. If you expose a mysql port on 3306 and then bind that port into a container, ( to host, from host ) then things become slow - the gateway mode. 

Generally, exposing a port is as fast as using them on the host - so for  performance reasons =host does play no role. But it probably becomes an issue since i guess all the actors/controllers will broadcast and also all the other devices like plex, gcast and all those, the broacast and AFAIC broadcast will not be available to the docker container and it will cost quiet some effort to route them into the container. But this is something i would have to look up.

In any way, this should be part of the docs, that this is yet most probably a convenience reason

**Comment by Santobert** [comment]
Sorry for bumping up this old thread. Besides HA, there are some more docker containers on my server and I want to take control of all exposed ports. For security reasons, I would also like to limit the abilities of each container by only exposing the ports it needs.
I'd appreciate it if there were a list of all ports needed for those who don't want to use host mode.
